version: "3.8"

services:
  frontend-service:
    container_name: frontend-app
    build:
      context: .
    restart: always
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
